slovak_treebank/sk_snk-ud-test.conllu:
	wget -P slovak_treebank https://raw.githubusercontent.com/UniversalDependencies/UD_Slovak-SNK/master/sk_snk-ud-test.conllu


slovak_treebank/sk_snk-ud-train.conllu:
	wget -P slovak_treebank https://raw.githubusercontent.com/UniversalDependencies/UD_Slovak-SNK/master/sk_snk-ud-train.conllu


